### ISSUE TITLE
spreadsheets doesn't work any more

### ISSUE THREAD

**Issue by akalinovskiy** [naveed-ahmad/google_docs_onebox#1]
`Refused to display 'https://docs.google.com/sharing/init?id=1IA_....…indowsEnabled=true&shareUiType=default&hl=en&authuser=1&rand=1440066700199' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

I suppose google have changed something inside their API.

**Comment by naveed-ahmad** [comment]
Sorry for late response @akalinovskiy, this plugin has been merged with official [one_box](https://github.com/discourse/onebox) gem long ago with some improvements.
